export const CREATE_VOUCHER_REQUEST='CREATE_VOUCHER_REQUEST'
export const CREATE_VOUCHER_SUCCESS='CREATE_VOUCHER_SUCCESS'
export const CREATE_VOUCHER_FAIL='CREATE_VOUCHER_FAIL'
export const CLEAR_ERRORS='CLEAR_ERRORS'